### ISSUE TITLE
Nick change request system

### ISSUE THREAD

**Issue by oodvg** [suvanl/delet3-suggestions#1]
Hello. Its me again! sorry i keep leaving so many suggestions! i feel bad.

anyhow, how about a nick change request system
user example, if the user doesnt have permissions to change a nick, a server moderator or higher can change it for them. which that may be the case.

bot example, sends a embed to the channel "nicks" (you should be able to change in config) with the username and id, old name, requesting name, and what time they requested it.

bot reacts to :heavy_check_mark: or :x:
if anyone with a permlevel or 2 or higher, can accept or denied it by reacting.

**Comment by suvanl** [comment]
Hey there, please don't feel bad about leaving so many suggestions! All suggestions are incredibly useful and are greatly appreciated :)

This seems like a useful system to implement, as it'd help solve the problem of admins disabling the "Change Nickname" permission on larger servers to prevent inappropriate nicknames being set.

This would be done through listening to the [`guildMemberUpdate`](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-guildMemberUpdate) event, and as this system will be behind a setting, it (hopefully) shouldn't be too taxing on memory usage, as this event will only be listened to on servers with this system enabled (via their settings).

**Comment by oodvg** [comment]
I was thinking about when someone does [prefix]nick [the nick they want]. The bot replys sending request in.

**Comment by suvanl** [comment]
Ah I see, this obviously makes more sense anyway (the thing I said about monitoring the `guildMemberUpdate` event doesn't even make sense in this situation, oops!)

Thanks a lot for clarifying this; this shouldn't be too tough to implement.

**Comment by oodvg** [comment]
No problem! Just wanted to clarify what I mean for the system. Also, probably set case numbers for moderation system and nick system. So moderator can remove a punishment with case numbers. Should of posted this in a new issue 😂. Sorry.

**Comment by suvanl** [comment]
Yep, case numbers have already been implemented!

**Comment by oodvg** [comment]
Alright. Thanks!

**Comment by suvanl** [comment]
Closing this as [delet3's repo](https://github.com/suvanl/delet3) is now public. More info: https://github.com/suvanl/delet3-suggestions/issues/10#issuecomment-782358605

I did actually start working on this suggestion, however, my hard drive was wiped recently and most of the code relating to this system hadn't been committed. I am still considering implementing this though, as it's a really handy suggestion. I've listed it on the "in progress" section of the completion roadmap project board here: https://github.com/suvanl/delet3/projects/1#card-48202428

If you have anything else to add regarding this suggestion, please create an issue on the new repo. Apologies for moving everything to yet another repo - but this move will be the final one (hopefully...)
