### ISSUE TITLE
global error logs (OWNER SERVER ONLY)

### ISSUE THREAD

**Issue by oodvg** [suvanl/delet3-suggestions#2]
global error log?
example, when you ban someone but the message doesn't go though. a error shows up there with the information. any errors if you warn,kick,mute someone and the users messages are disabled. all information goes there. this should also be a logs for discord api errors if something goes wrong or you get error in console.

**Comment by suvanl** [comment]
This could be a nice feature for people self-hosting the bot, as it would mean that they don't have to look at the console to see such errors. Unfortunately, self-hosting is more of a long-term consideration at the moment, and there aren't currently any plans to make it possible/easy in the near future.

Also, all errors are currently logged to the console anyway (including uncaught errors, which wouldn't show up as embeds), and the console output is clear and uses colours to aid clarity. People who self-host the bot would need to use a terminal anyway to start/stop the bot, so using the console to see errors and info messages shouldn't be too much of a problem.
