### ISSUE TITLE
Setup command

### ISSUE THREAD

**Issue by oodvg** [suvanl/delet3-suggestions#4]
Setup command

Example, [prefix]setup.
Bot replys, what do you want the prefix to be?
User import [prefix]
Bot replys, what do you want logs to be?
User imports [logs]
Bot replys, what do you want moderation role to be? Please mention.
User imports @[Mod role]
Bot replys, what do you want the administration role to be? Please mention.
User imports @[Admin role]

**Comment by oodvg** [comment]
Bot replys, okay! Setup is complete. Please do /set view to check it and /set edit for changing

**Comment by suvanl** [comment]
Something like this has already been implemented into delet3 - the only difference being, a single command controls each category (e.g. `[prefix]modlog` sends prompts allowing the user to change all modlog-related settings), to prevent unnecessary prompts for settings the user doesn't want to change.

**Comment by oodvg** [comment]
oh. okay.
