### ISSUE TITLE
Using lavalink for high quality music streaming

### ISSUE THREAD

**Issue by 0zul** [suvanl/delet3-suggestions#5]
Tons of music commands which supports lavalink and tons of filters like bass bassboost, soft, treble etc. I also have a Repository for hosting Lavalink on Heroku Ceder stack. [Click here to see the repo](https://github.com/IamTheRealSami/LavalinkOnHeroku). I'm also available on Discord, Feel free to dm me at ``Error#0003``. I can suggest you with a lot of new things and help you here-and-there.

**Comment by suvanl** [comment]
This is an interesting suggestion, especially given that the music system for delet3 hasn't been written yet. I'll look into this sometime soon and will get back to you.

**Comment by 0zul** [comment]
@suvanl I'd love to talk to you on Discord if possible. Add me and let's have a chat. 🙂

**Comment by suvanl** [comment]
Hey,

delet3's source code is now public and exists here: https://github.com/suvanl/delet3.
All future issues/pull requests regarding delet should be created on the delet3 repository.

Unfortunately, I still haven't got round to implementing music streaming, but I think I will be using Lavalink when it comes to doing so. I've created a card for this suggestion in the "to do" section of the Completion Roadmap project board: https://github.com/suvanl/delet3/projects/1#card-48202469

If you have anything else to add regarding this suggestion, please create an issue on the new repo.
