### ISSUE TITLE
an bot owner/admin prefix

### ISSUE THREAD

**Issue by oodvg** [suvanl/delet3-suggestions#7]
Hey! its me again and i didn't see this suggestion yet.

lets say that a guild messed up the config for the guild and they asked the bot owner or someone that has permission to delete the guild config. yes, i understand that bot admins/support has eval but we don't need eval
admin prefix can be whatever you developer wants.

only bot owners, support, and bot admins can use this in any server.
[admin prefix]set view to see the guild config
[admin prefix]reset all to reset the guild config (this includes the pt system and everything with the guild)

**Comment by oodvg** [comment]
also, for delet3, there should at least be a getconf cmd and getinvite (backdoor) to check the support the users needed help on with the bot.

**Comment by oodvg** [comment]
also, let me know if you need a tester or something. ill be happy to help

**Comment by suvanl** [comment]
An option to reset the guild config/settings back to default has already been implemented, in the form of a `%default` command (with a minimum permLevel of Server Admin). It'd make much more sense to give server admins/owners the option to reset their settings to default, as they can change other settings anyway. Restoring defaults is just like changing all settings in one go.

If this command is limited to the bot owner (or bot admins), users will have to invite the bot owner/admin to their server, just to reset their settings, which isn't very convenient. The bot owner can run the `%settings` command in any server anyway, (as the min. permLevel is Server Admin, and Bot Owner is above this).

On the topic of getConf - all guild settings are stored in a MongoDB collection, and each guild can be queried (by guild ID), via a REST API*, so there isn't any need for a command of such nature. As for getInvite, I feel like this would violate user privacy to some extent - users invite the bot to their server, not the bot owner as well. Having someone suddenly join your server uninvited would be quite an odd surprise! If a user wants to invite the bot owner to their server, they can generate an invite themselves and send it to the owner, if required. This is more secure as the invite would've been generated by a member of the server (with sufficient perms to create invites), by choice.

*this will become clearer once delet3's source code becomes public (which should be soon!)
